version: '3.8'
services:
  # 1. Elasticsearch for Full-Text Search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: es-onebox
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 2. Qdrant (Vector Database) for RAG
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-onebox
    ports:
      - 6333:6333 # REST API
      - 6334:6334 # gRPC
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  esdata:
    driver: local
  qdrant_storage:
    driver: local
